EXAMPLE_BIN=hsvsprite
OBJF = ./Sources/hsv_sprite_batch.o \
./Sources/hsv_sprite.o \
./Sources/precomp.o \
./Sources/hsv.o

LIBS=clanApp clanDisplay clanCore clanGL clanVK

include ../../Makefile.conf

# EOF #

