EXAMPLE_BIN=texturegroup
OBJF = \
./Sources/atlas.o \
./Sources/precomp.o \
./Sources/theme.o \
./Sources/options.o

CXXFLAGS += -I Sources -I ./
LIBS=clanApp clanDisplay clanCore clanGL clanVK clanUI

include ../../Makefile.conf

# EOF #

