EXAMPLE_BIN=colorwheel
OBJF = ./Sources/colorwheel.o \
./Sources/app.o \
./Sources/theme.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL clanVK clanUI
CXXFLAGS += -I Sources -I./

include ../../Makefile.conf

# EOF #

